#!/usr/bin/env node

const correct = [1, 2, 3];
const userAnswer = [1, 1, 3, 4];

function findIncorrectIndexes(correct, userAnswer) {
  const incorrectIndexes = [];
  for (let i = 0; i < correct.length; i++) {
    if (correct[i] !== userAnswer[i]) {
      incorrectIndexes.push(i);
    }
  }
  return incorrectIndexes; // [ 1, 3 ]
}

function printWithHighlight(userAnswer, incorrectIndexes) {
  // const userAnswer = text.split(" ");
  const highlightedText = userAnswer
    .map(
      (userAnswer, index) =>
        // incorrectIndexes [ 1, 3 ] に userAnswerの各インデックスを照合し
        // 合致するものは反転表示
        incorrectIndexes.includes(index)
          ? `\x1b[7m${userAnswer}\x1b[0m` // 合致するので反転表示
          : userAnswer // 合致しないのでそのまま表示
    )
    .join(" ");

  console.log(highlightedText);
}

printWithHighlight(userAnswer, findIncorrectIndexes(userAnswer, correct));
