#!/usr/bin/env node

const correctAnswer = [1, 2, 3];
const userAnswer = [1, 1, 3, 4];

function findIncorrectIndexes(correctAnswer, userAnswer) {
  const incorrectIndexes = [];
  // 基準は correctAnswer.length
  for (let i = 0; i < correctAnswer.length; i++) {
    if (correctAnswer[i] !== userAnswer[i]) {
      incorrectIndexes.push(i);
    }
  }
  return incorrectIndexes; // [ 1 ]
}

function printWithHighlight(userAnswer, incorrectIndexes) {
  // const userAnswer = text.split(" ");
  const highlightedText = userAnswer
    .map(
      (userAnswer, index) =>
        // incorrectIndexes [ 1 ] に userAnswerの各インデックスを照合し
        // 合致するものは反転表示
        incorrectIndexes.includes(index)
          ? `\x1b[7m${userAnswer}\x1b[0m` // 合致するので反転表示
          : userAnswer // 合致しないのでそのまま表示
    )
    .join(" ");

  console.log(highlightedText);
}

printWithHighlight(userAnswer, findIncorrectIndexes(correctAnswer, userAnswer));



// \e[0m ・・ 文字の装飾をリセットする
// \e[7m ・・ 反転させる（前景色と背景色を入れ替える）
