#!/usr/bin/env node

const correctAnswer = [1, 2, 3, 4, 5];
const userAnswer = [1, 3, 4];

function findIncorrectIndexes(correctAnswer, userAnswer) {
  // ① findIncorrectIndexes(userAnswer, correctAnswer)で呼び出すと、
  console.log(correctAnswer); // [1, 3, 4] userAnswer が出力される
  const incorrectIndexes = [];
  // 基準は correctAnswer.length
  for (let i = 0; i < correctAnswer.length; i++) {
    if (correctAnswer[i] !== userAnswer[i]) {
      incorrectIndexes.push(i);
    }
  }
  return incorrectIndexes;
}

console.log(findIncorrectIndexes(correctAnswer, userAnswer)); // => [ 1, 2, 3, 4 ]

// 呼び出し元の引数を逆にすると、結果が変わるので注意。
// 引数が複数のときは、呼び出し元の引数の順番が適用される。仮引数の順番は関係ない。
console.log(findIncorrectIndexes(userAnswer, correctAnswer)); // => [ 1, 2 ] 仮引数と逆にする。 ・・①
